stages:
- stage: Test
  displayName: 'Run Karate Tests'
  jobs:
  - deployment: RunKarate
    displayName: 'Execute Karate Tests'
    environment: 'QA-Test-Env'
    pool:
      name: 'Default'
    variables:
      # Azure DevOps configuration
      ADO_ORG: 'ngatran283'                  # your Azure DevOps org
      ADO_PROJECT: 'demo'          # your Azure DevOps project
      ADO_PAT: $(PersonalAccessToken)    # secret PAT stored in pipeline
      ADO_TEST_PLAN_ID: '3'          # your Test Plan ID
      ADO_TEST_SUITE_ID: '5'         # optional, target specific suite
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            
            - script: |
                  echo "Setting JAVA_HOME to Oracle JDK 17"
                  export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home
                  export PATH=$JAVA_HOME/bin:$PATH
                  java --version
            - task: Maven@4
              displayName: 'Maven Build'
              inputs:
                mavenPomFile: 'pom.xml'
                goals: 'clean install -DskipTests'
                mavenVersionOption: 'Default'

            - script: |
                mvn test
              displayName: 'Run Karate Tests'

            - task: PublishHtmlReport@1
              inputs:
                reportDir: 'target/karate-reports'
                reportTitle: 'Karate Test Html Report $(Build.BuildId)'
                condition:
                  succeededOrFailed()   

            - task: PublishTestResults@2
              inputs:
                testResultsFormat: 'JUnit'
                testResultsFiles: 'target/surefire-reports/TEST-*.xml'
                testRunTitle: 'Karate Test Run $(Build.BuildId)'
                mergeTestResults: true
                publishRunAttachments: true
              condition:
                succeededOrFailed()                  

            - task: NodeTool@0
              inputs:
                versionSpec: '18.x'
              condition:
                succeededOrFailed()
            
            # 5️⃣ Update Azure DevOps Test Plan with Karate results
            - script: |
                node updateTestPlan.js
              displayName: 'Update Azure DevOps Test Plan with Karate Results'
              env:
                ADO_ORG: $(ADO_ORG)
                ADO_PROJECT: $(ADO_PROJECT)
                ADO_PAT: $(ADO_PAT)
                ADO_TEST_PLAN_ID: $(ADO_TEST_PLAN_ID)
                ADO_TEST_SUITE_ID: $(ADO_TEST_SUITE_ID)
                TEST_REPORT_FILE: 'target/surefire-reports/TEST-*.xml'
                BUILD_BUILDID: $(Build.BuildId)
              condition:
                succeededOrFailed()