stages:
- stage: Test
  displayName: 'Run Karate Tests'
  jobs:
  - deployment: RunKarate
    displayName: 'Execute Karate Tests'
    environment: 'QA-Test-Env'
    pool:
      name: 'Default'
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            
            - script: |
                  echo "Setting JAVA_HOME to Oracle JDK 17"
                  export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home
                  export PATH=$JAVA_HOME/bin:$PATH
                  java --version
            - task: Maven@4
              displayName: 'Maven Build'
              inputs:
                mavenPomFile: 'pom.xml'
                goals: 'clean install -DskipTests'
                mavenVersionOption: 'Default'

            - script: |
                mvn test -Dkarate.options="--tags @smoke" -Dkarate.output.dir=$(Build.ArtifactStagingDirectory)/surefire-reports
              displayName: 'Run Karate Tests'

            - task: PublishTestResults@2
              inputs:
                testResultsFormat: 'JUnit'
                testResultsFiles: '**/$(Build.ArtifactStagingDirectory)/surefire-reports/TEST-*.xml'
                testRunTitle: 'Karate Test Run $(Build.BuildId)'
                mergeTestResults: true
                publishRunAttachments: true

            - task: NodeTool@0
              inputs:
                versionSpec: '18.x'