trigger:
- main

pool:
  name: 'Default'

steps:
- task: Maven@4
  displayName: 'Build Project'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install -DskipTests'

# Publish the build output as artifact
- publish: $(System.DefaultWorkingDirectory)
  artifact: drop
