trigger: none

parameters:
- name: tcmRunId
  type: string
  default: ''
  displayName: 'Test Run ID (leave empty for all tests)'

- name: karateTags
  type: string
  default: '@smoke'
  displayName: 'Karate Tags (e.g., @smoke, @regression)'

- name: adoTestPlanId
  type: string
  default: '3'
  displayName: 'Azure DevOps Test Plan ID'

- name: adoTestSuiteId
  type: string
  default: '5'
  displayName: 'Azure DevOps Test Suite ID (optional)'

stages:

# ---------------------------
# Stage 1: Build
# ---------------------------
- stage: Build
  displayName: "Build Stage"
  jobs:
    - job: BuildJob
      displayName: "Compile and Package"
      pool:
        name: 'Default'
      steps:
        - checkout: self

        # Maven build
        - task: Maven@4
          displayName: 'Maven Build (skip tests)'
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean install -DskipTests'
            mavenVersionOption: 'Default'

        # Publish build artifact
        - publish: $(System.DefaultWorkingDirectory)/target
          artifact: drop

# ---------------------------
# Stage 2: Test
# ---------------------------
- stage: Test
  displayName: 'Run Karate Tests'
  dependsOn: Build
  jobs:
    - deployment: RunKarate
      displayName: 'Execute Karate Tests'
      environment: 'QA-Test-Env'
      pool:
        name: 'Default'
      variables:
        ADO_ORG: 'ngatran283'
        ADO_PROJECT: 'demo'
        ADO_PAT: $(PersonalAccessToken)
        testReportFile: 'target/surefire-reports/TEST-TestRunner.xml'
        testReportHtmlFile: 'target/karate-reports/karate-summary.html'
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: drop

              # Show execution mode
              - script: |
                  if [ "${{ parameters.tcmRunId }}" != "" ]; then
                    echo "Running from Azure Test Plan Run ID: ${{ parameters.tcmRunId }}"
                  else
                    echo "Running all Karate tests with tags: ${{ parameters.karateTags }}"
                  fi
                displayName: 'Show Execution Mode'

              # Setup Java
              - script: |
                  echo "Setting JAVA_HOME to Oracle JDK 17"
                  export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home
                  export PATH=$JAVA_HOME/bin:$PATH
                  java --version
                displayName: 'Setup Java 17'

              # Run tests from Azure Test Plan if tcmRunId is provided
              - ${{ if ne(parameters.tcmRunId, '') }}:
                - task: VSTest@2
                  displayName: 'Run Tests from Azure Test Plan'
                  inputs:
                    testSelector: 'testPlan'
                    tcmRunId: ${{ parameters.tcmRunId }}
                    searchFolder: '$(System.DefaultWorkingDirectory)'
                    vsTestVersion: 'latest'

              # Run Karate tests if no tcmRunId provided
              - ${{ if eq(parameters.tcmRunId, '') }}:
                - script: |
                    mvn test -Dkarate.options="--tags ${{ parameters.karateTags }}"
                  displayName: 'Run Karate Tests'

              # Optional Node.js script for updating Test Plan
              - task: NodeTool@0
                inputs:
                  versionSpec: '20.x'
                condition: succeededOrFailed()
              - script: |
                  node updateTestPlan.js
                displayName: 'Update Azure DevOps Test Plan with Karate Results'
                env:
                  ADO_ORG: $(ADO_ORG)
                  ADO_PROJECT: $(ADO_PROJECT)
                  ADO_PAT: $(ADO_PAT)
                  ADO_TEST_PLAN_ID: ${{ parameters.adoTestPlanId }}
                  ADO_TEST_SUITE_ID: ${{ parameters.adoTestSuiteId }}
                  TEST_REPORT_FILE: $(testReportFile)
                  TEST_REPORT_HTML_FILE: $(testReportHtmlFile)
                  BUILD_BUILDID: $(Build.BuildId)
                condition: succeededOrFailed()
