trigger: none

parameters:
- name: karateTags
  type: string
  default: '@smoke'
  displayName: 'Karate Tags (e.g., @smoke, @regression)'

- name: adoTestPlanId
  type: string
  default: '3'
  displayName: 'Azure DevOps Test Plan ID'

- name: adoTestSuiteId
  type: string
  default: '5'
  displayName: 'Azure DevOps Test Suite ID (optional)'

stages:
- stage: Test
  displayName: 'Run Karate Tests'
  jobs:
    - deployment: RunKarate
      displayName: 'Execute Karate Tests'
      environment: 'QA-Test-Env'
      pool:
        vmImage: 'ubuntu-latest'
      variables:
        ADO_ORG: 'ngatran283'
        ADO_PROJECT: 'demo'
        ADO_PAT: $(PersonalAccessToken)
        testReportFile: 'target/surefire-reports/TEST-TestRunner.xml'
        testReportHtmlFile: 'target/karate-reports/karate-summary.html'
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self

              # Show execution mode
              - script: |
                  echo "Running Karate tests with tags: ${{ parameters.karateTags }}"
                displayName: 'Show Execution Mode'

              # Setup Java
              - script: |
                  sudo apt-get update
                  sudo apt-get install -y openjdk-17-jdk
                  export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
                  export PATH=$JAVA_HOME/bin:$PATH
                  java --version
                displayName: 'Setup Java 17'

              # Run Karate tests using Maven
              - script: |
                  mvn test -Dkarate.options="--tags ${{ parameters.karateTags }}"
                displayName: 'Run Karate Tests'

              # Optional Node.js script
              - task: NodeTool@0
                inputs:
                  versionSpec: '20.x'
              - script: |
                  node updateTestPlan.js
                displayName: 'Update Azure DevOps Test Plan with Karate Results'
                env:
                  ADO_ORG: $(ADO_ORG)
                  ADO_PROJECT: $(ADO_PROJECT)
                  ADO_PAT: $(ADO_PAT)
                  ADO_TEST_PLAN_ID: ${{ parameters.adoTestPlanId }}
                  ADO_TEST_SUITE_ID: ${{ parameters.adoTestSuiteId }}
                  TEST_REPORT_FILE: $(testReportFile)
                  TEST_REPORT_HTML_FILE: $(testReportHtmlFile)
                  BUILD_BUILDID: $(Build.BuildId)
